controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

scraper_index:
  path: /scraper
  controller: App\Controller\ScraperController::index
  methods: GET

scraper_create:
  path: /scraper/create
  controller: App\Controller\ScraperController::create
  methods: GET

scraper_store:
  path: /scraper/store
  controller: App\Controller\ScraperController::store
  methods: POST

scraper_destroy:
  path: /scraper/destroy/{id}
  controller: App\Controller\ScraperController::destroy
  methods: [POST]
